import type { Activity } from '@/lib/types'

export const ACTIVITIES: Activity[] = [
  {
    id: 'act-001',
    type: 'lead_added',
    titleAr: 'عميل محتمل جديد',
    descriptionAr: 'تم إضافة زياد الصقر — إحالة من عميل VIP، اهتمام بتاون هاوس في الرياض',
    entityId: 'lead-006',
    entityType: 'lead',
    date: '2026-06-03T10:00:00Z',
    salesRepId: 'rep-003',
    customerNameAr: 'زياد عمر الصقر',
  },
  {
    id: 'act-002',
    type: 'ticket_created',
    titleAr: 'تذكرة حرجة جديدة',
    descriptionAr: 'TKT-2406-001: فشل التحقق من الهوية عبر نافذ — يؤثر على عمليات متعددة',
    entityId: 'TKT-2406-001',
    entityType: 'ticket',
    date: '2026-06-03T11:58:00Z',
  },
  {
    id: 'act-003',
    type: 'interaction_logged',
    titleAr: 'مكالمة متابعة',
    descriptionAr: 'خالد الشمري: متابعة طلب تمويل مشروع السدرة مع بنك الراجحي',
    entityId: 'int-027',
    entityType: 'customer',
    date: '2026-06-03T09:00:00Z',
    salesRepId: 'rep-001',
    customerNameAr: 'خالد راشد الشمري',
  },
  {
    id: 'act-004',
    type: 'lead_added',
    titleAr: 'عميل محتمل جديد',
    descriptionAr: 'يوسف الحارثي — قادم من تويتر، شقة في جدة بميزانية ٦٥٠ ألف ريال',
    entityId: 'lead-002',
    entityType: 'lead',
    date: '2026-06-02T14:00:00Z',
    salesRepId: 'rep-002',
    customerNameAr: 'يوسف محمد الحارثي',
  },
  {
    id: 'act-005',
    type: 'stage_changed',
    titleAr: 'تقدم في خط المبيعات',
    descriptionAr: 'محمد الرشودي انتقل من "مؤهَّل" إلى "عرض سعر" — فيلا بـ٣.٥ مليون ريال',
    entityId: 'lead-015',
    entityType: 'lead',
    date: '2026-06-01T10:00:00Z',
    salesRepId: 'rep-001',
    customerNameAr: 'محمد إبراهيم الرشودي',
  },
  {
    id: 'act-006',
    type: 'interaction_logged',
    titleAr: 'رسالة واتساب',
    descriptionAr: 'منيرة الحميدي: إرسال كتالوج مشروع الياسمين وأسعار الشقق',
    entityId: 'cust-012',
    entityType: 'customer',
    date: '2026-06-01T14:00:00Z',
    salesRepId: 'rep-008',
    customerNameAr: 'منيرة حمد الحميدي',
  },
  {
    id: 'act-007',
    type: 'opportunity_created',
    titleAr: 'فرصة جديدة',
    descriptionAr: 'أحمد العتيبي: دوبلكس في مشروع وادي الملك — احتمالية ٣٠٪',
    entityId: 'opp-007',
    entityType: 'opportunity',
    date: '2026-05-31T09:00:00Z',
    salesRepId: 'rep-004',
    customerNameAr: 'أحمد فيصل العتيبي',
  },
  {
    id: 'act-008',
    type: 'contract_signed',
    titleAr: 'عقد موقّع',
    descriptionAr: 'سارة المالكي وقّعت عقد شراء شقة في مشروع الياسمين بقيمة ٦٨٠ ألف ريال',
    entityId: 'cnt-006',
    entityType: 'contract',
    date: '2026-05-28T10:00:00Z',
    salesRepId: 'rep-002',
    customerNameAr: 'سارة محمد المالكي',
  },
  {
    id: 'act-009',
    type: 'campaign_sent',
    titleAr: 'حملة مُرسَلة',
    descriptionAr: 'حملة إعادة تفعيل العملاء الخاملين: ٣٤٢ رسالة — ١٢ تحويل حتى الآن',
    entityId: 'camp-003',
    entityType: 'campaign',
    date: '2026-05-28T09:00:00Z',
    salesRepId: 'rep-003',
  },
  {
    id: 'act-010',
    type: 'score_updated',
    titleAr: 'تحديث درجة الذكاء الاصطناعي',
    descriptionAr: 'نواف الرشيدي: درجة AI ارتفعت من ٧٢ إلى ٧٧ — اهتمام متزايد بالفيلا',
    entityId: 'lead-013',
    entityType: 'lead',
    date: '2026-05-28T08:00:00Z',
    customerNameAr: 'نواف عبدالله الرشيدي',
  },
  {
    id: 'act-011',
    type: 'stage_changed',
    titleAr: 'تقدم في خط المبيعات',
    descriptionAr: 'إيمان الحربي انتقلت من "تم التواصل" إلى "مؤهَّل" — تاون هاوس مكة',
    entityId: 'lead-011',
    entityType: 'lead',
    date: '2026-05-27T15:00:00Z',
    salesRepId: 'rep-006',
    customerNameAr: 'إيمان طارق الحربي',
  },
  {
    id: 'act-012',
    type: 'interaction_logged',
    titleAr: 'زيارة ميدانية',
    descriptionAr: 'أحمد العتيبي: زار مشروع وادي الملك — مهتم بالدوبلكس الركني',
    entityId: 'cust-005',
    entityType: 'customer',
    date: '2026-05-26T10:00:00Z',
    salesRepId: 'rep-004',
    customerNameAr: 'أحمد فيصل العتيبي',
  },
  {
    id: 'act-013',
    type: 'ticket_created',
    titleAr: 'تذكرة دعم فني',
    descriptionAr: 'TKT-2406-007: عقد سارة المالكي لم يظهر بعد التوقيع الرقمي — تم الحل',
    entityId: 'TKT-2406-007',
    entityType: 'ticket',
    date: '2026-05-29T10:00:00Z',
  },
  {
    id: 'act-014',
    type: 'opportunity_created',
    titleAr: 'فرصة جديدة',
    descriptionAr: 'لينا الصالحي: شقة مطلة على الحديقة في مشروع السدرة — ٨٢٠ ألف ريال',
    entityId: 'opp-010',
    entityType: 'opportunity',
    date: '2026-05-26T09:00:00Z',
    salesRepId: 'rep-007',
    customerNameAr: 'لينا صالح الصالحي',
  },
  {
    id: 'act-015',
    type: 'interaction_logged',
    titleAr: 'اجتماع',
    descriptionAr: 'عبدالله القحطاني: اجتماع لتقديم عرض تاون هاوس النخيل — العميل يطلب خصمًا',
    entityId: 'cust-003',
    entityType: 'customer',
    date: '2026-05-25T10:00:00Z',
    salesRepId: 'rep-003',
    customerNameAr: 'عبدالله خالد القحطاني',
  },
  {
    id: 'act-016',
    type: 'score_updated',
    titleAr: 'تحديث درجة الذكاء الاصطناعي',
    descriptionAr: 'محمد الرشودي: درجة AI وصلت ٨٢ — مرشح أقوى لإغلاق الصفقة',
    entityId: 'lead-015',
    entityType: 'lead',
    date: '2026-06-01T10:00:00Z',
    customerNameAr: 'محمد إبراهيم الرشودي',
  },
  {
    id: 'act-017',
    type: 'campaign_sent',
    titleAr: 'حملة مُكتملة',
    descriptionAr: 'حملة إطلاق مشروع السدرة: ١٢٤٠ رسالة — ٨٧ تحويل (٧٪)',
    entityId: 'camp-001',
    entityType: 'campaign',
    date: '2026-04-30T09:00:00Z',
    salesRepId: 'rep-001',
  },
  {
    id: 'act-018',
    type: 'contract_signed',
    titleAr: 'عقد موقّع',
    descriptionAr: 'محمد الزهراني: فيلا مشروع السدرة بقيمة ٣.٢ مليون ريال',
    entityId: 'cnt-001',
    entityType: 'contract',
    date: '2026-05-10T10:00:00Z',
    salesRepId: 'rep-001',
    customerNameAr: 'محمد عبدالله الزهراني',
  },
  {
    id: 'act-019',
    type: 'lead_added',
    titleAr: 'عميل محتمل جديد',
    descriptionAr: 'حنان الرشيدي — قادمة من حملة SMS، شقة في الدمام',
    entityId: 'lead-003',
    entityType: 'lead',
    date: '2026-06-01T10:00:00Z',
    salesRepId: 'rep-004',
    customerNameAr: 'حنان عبدالرحمن الرشيدي',
  },
  {
    id: 'act-020',
    type: 'stage_changed',
    titleAr: 'تقدم في خط المبيعات',
    descriptionAr: 'سلطان الدوسري: من "جديد" إلى "تم التواصل" — مهتم بفيلا في الرياض',
    entityId: 'lead-004',
    entityType: 'lead',
    date: '2026-05-31T16:00:00Z',
    salesRepId: 'rep-001',
    customerNameAr: 'سلطان ماجد الدوسري',
  },
]
