import type { Campaign } from '@/lib/types'

export const CAMPAIGNS: Campaign[] = [
  // ── Completed ────────────────────────────────────────────────────────────────
  {
    id: 'camp-001',
    nameAr: 'حملة رمضان العقارية ٢٠٢٦',
    type: 'ترويجية',
    descriptionAr: 'حملة موجهة لعملاء الفيلات والتاون هاوس خلال شهر رمضان',
    channels: ['WhatsApp', 'SMS', 'Email'],
    audience: { city: ['الرياض', 'جدة'], propertyInterest: ['فيلا', 'تاون هاوس'], estimatedReach: 1240 },
    messageTemplate: { body: 'عروض رمضان الحصرية من NHC — وحدات فاخرة بأسعار استثنائية. اتصل بنا اليوم!', variables: ['{customer_name}'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-03-01T08:00:00Z' },
    status: 'Completed',
    metrics: { sent: 1240, delivered: 1198, opened: 876, clicked: 312, converted: 42 },
    createdAt: '2026-02-20T10:00:00Z',
    createdBy: 'rep-001',
  },
  {
    id: 'camp-002',
    nameAr: 'حملة العيد — مشروع السدرة',
    type: 'إطلاق مشروع',
    descriptionAr: 'إطلاق المرحلة الثانية من مشروع السدرة مع عروض العيد',
    channels: ['WhatsApp', 'Social'],
    audience: { city: ['الرياض'], propertyInterest: ['فيلا'], leadStage: ['Qualified', 'Proposal'], estimatedReach: 580 },
    messageTemplate: { body: 'نبارك لكم العيد — وحدات جديدة في السدرة متاحة الآن! سارع بالتسجيل.', variables: ['{customer_name}', '{property_type}'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-04-08T09:00:00Z' },
    status: 'Completed',
    metrics: { sent: 580, delivered: 564, opened: 420, clicked: 187, converted: 28 },
    createdAt: '2026-04-01T10:00:00Z',
    createdBy: 'rep-002',
  },
  {
    id: 'camp-005',
    nameAr: 'حملة الإشغال الكامل — برج الياسمين',
    type: 'إطلاق مشروع',
    descriptionAr: 'تسويق آخر الوحدات المتبقية في برج الياسمين بجدة',
    channels: ['WhatsApp', 'Email', 'Web'],
    audience: { city: ['جدة'], propertyInterest: ['شقة', 'دوبلكس'], estimatedReach: 730 },
    messageTemplate: { body: 'فرصتك الأخيرة في برج الياسمين — وحدات محدودة بجدة! {property_type} بدفعة أولى ٥٪.', variables: ['{customer_name}', '{property_type}'] },
    schedule: { type: 'scheduled', scheduledAt: '2025-12-10T08:00:00Z' },
    status: 'Completed',
    metrics: { sent: 730, delivered: 698, opened: 487, clicked: 201, converted: 31 },
    createdAt: '2025-12-01T10:00:00Z',
    createdBy: 'rep-002',
  },
  // ── Active ────────────────────────────────────────────────────────────────────
  {
    id: 'camp-003',
    nameAr: 'حملة العملاء غير النشطين',
    type: 'إعادة تفعيل',
    descriptionAr: 'إعادة التواصل مع العملاء الذين لم يُتواصل معهم منذ أكثر من ٣٠ يوماً',
    channels: ['SMS', 'Email'],
    audience: { lastInteractionDays: 30, estimatedReach: 340 },
    messageTemplate: { body: 'مرحباً {customer_name}، نود إعلامك بتوافر وحدات جديدة تناسب اهتمامك. تواصل معنا لمعرفة التفاصيل.', variables: ['{customer_name}'] },
    schedule: { type: 'immediate' },
    status: 'Active',
    metrics: { sent: 200, delivered: 194, opened: 112, clicked: 38, converted: 5 },
    createdAt: '2026-05-15T08:00:00Z',
    createdBy: 'rep-003',
  },
  {
    id: 'camp-006',
    nameAr: 'حملة الوعي بمشروع نجران هيلز',
    type: 'تثقيفية',
    descriptionAr: 'التعريف بمشروع نجران هيلز وخصائصه للعملاء المهتمين بالجنوب',
    channels: ['Social', 'Web'],
    audience: { city: ['أبها'], estimatedReach: 420 },
    messageTemplate: { body: 'هل تعرف مشروع نجران هيلز؟ وحدات راقية في قلب الجنوب بأسعار تنافسية. اكتشف المزيد.', variables: ['{customer_name}'] },
    schedule: { type: 'immediate' },
    status: 'Active',
    metrics: { sent: 310, delivered: 298, opened: 165, clicked: 72, converted: 9 },
    createdAt: '2026-05-20T09:00:00Z',
    createdBy: 'rep-008',
  },
  // ── Scheduled ─────────────────────────────────────────────────────────────────
  {
    id: 'camp-004',
    nameAr: 'حملة صيف ٢٠٢٦ — شقق جدة',
    type: 'ترويجية',
    descriptionAr: 'عروض خاصة على شقق جدة لصيف ٢٠٢٦',
    channels: ['WhatsApp', 'Social', 'Email'],
    audience: { city: ['جدة'], propertyInterest: ['شقة', 'دوبلكس'], estimatedReach: 820 },
    messageTemplate: { body: 'عروض الصيف في جدة — {property_type} فاخرة بدفعة أولى ١٠٪ فقط!', variables: ['{customer_name}', '{property_type}'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-06-15T09:00:00Z' },
    status: 'Scheduled',
    metrics: { sent: 0, delivered: 0, opened: 0, clicked: 0, converted: 0 },
    createdAt: '2026-06-01T10:00:00Z',
    createdBy: 'rep-005',
  },
  {
    id: 'camp-007',
    nameAr: 'حملة الخريف — فلل الرياض',
    type: 'موسمية',
    descriptionAr: 'عروض موسم الخريف على الفلل الفاخرة في الرياض',
    channels: ['WhatsApp', 'SMS'],
    audience: { city: ['الرياض'], propertyInterest: ['فيلا', 'تاون هاوس'], leadStage: ['Qualified', 'Proposal'], estimatedReach: 640 },
    messageTemplate: { body: 'موسم الخريف يبدأ بفيلا أحلامك في الرياض — عروض حصرية حتى نهاية أكتوبر. {customer_name}، لا تفوّت الفرصة!', variables: ['{customer_name}', '{property_type}'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-09-01T08:00:00Z' },
    status: 'Scheduled',
    metrics: { sent: 0, delivered: 0, opened: 0, clicked: 0, converted: 0 },
    createdAt: '2026-06-02T11:00:00Z',
    createdBy: 'rep-001',
  },
  // ── Draft ─────────────────────────────────────────────────────────────────────
  {
    id: 'camp-008',
    nameAr: 'حملة تمويل بنك الراجحي ٢٠٢٦',
    type: 'ترويجية',
    descriptionAr: 'حملة مشتركة مع بنك الراجحي بتمويل صفري ٦ أشهر',
    channels: ['WhatsApp', 'Email', 'Social'],
    audience: { leadStage: ['New', 'Contacted'], estimatedReach: 980 },
    messageTemplate: { body: 'بالتعاون مع بنك الراجحي — تمويل بدون فوائد لأول ٦ أشهر على {property_type} في مشاريع NHC!', variables: ['{customer_name}', '{property_type}'] },
    schedule: { type: 'immediate' },
    status: 'Draft',
    metrics: { sent: 0, delivered: 0, opened: 0, clicked: 0, converted: 0 },
    createdAt: '2026-06-03T09:00:00Z',
    createdBy: 'rep-003',
  },
]

export const getCampaignById = (id: string) => CAMPAIGNS.find((c) => c.id === id)
