import type { Campaign } from '@/lib/types'

export const CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-001',
    nameAr: 'حملة رمضان العقارية ٢٠٢٦',
    type: 'ترويجية',
    descriptionAr: 'حملة موجهة لعملاء الفيلات والتاون هاوس خلال شهر رمضان',
    channels: ['WhatsApp', 'SMS', 'Email'],
    audience: { city: ['الرياض', 'جدة'], propertyInterest: ['فيلا', 'تاون هاوس'], estimatedReach: 1240 },
    messageTemplate: { body: 'عروض رمضان الحصرية من NHC — وحدات فاخرة بأسعار استثنائية. اتصل بنا اليوم!', variables: ['name'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-03-01T08:00:00Z' },
    status: 'Completed',
    metrics: { sent: 1240, delivered: 1198, opened: 876, clicked: 312, converted: 42 },
    createdAt: '2026-02-20T10:00:00Z',
    createdBy: 'rep-001',
  },
  {
    id: 'camp-002',
    nameAr: 'حملة العيد — مشروع السدرة',
    type: 'إطلاق مشروع',
    descriptionAr: 'إطلاق المرحلة الثانية من مشروع السدرة مع عروض العيد',
    channels: ['WhatsApp', 'Social'],
    audience: { city: ['الرياض'], propertyInterest: ['فيلا'], leadStage: ['Qualified', 'Proposal'], estimatedReach: 580 },
    messageTemplate: { body: 'نبارك لكم العيد — وحدات جديدة في السدرة متاحة الآن! سارع بالتسجيل.', variables: ['name', 'project'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-04-08T09:00:00Z' },
    status: 'Completed',
    metrics: { sent: 580, delivered: 564, opened: 420, clicked: 187, converted: 28 },
    createdAt: '2026-04-01T10:00:00Z',
    createdBy: 'rep-002',
  },
  {
    id: 'camp-003',
    nameAr: 'حملة العملاء غير النشطين',
    type: 'إعادة تفعيل',
    descriptionAr: 'إعادة التواصل مع العملاء الذين لم يُتواصل معهم منذ أكثر من ٣٠ يوماً',
    channels: ['SMS', 'Email'],
    audience: { lastInteractionDays: 30, estimatedReach: 340 },
    messageTemplate: { body: 'مرحباً، نود إعلامك بتوافر وحدات جديدة تناسب اهتمامك. تواصل معنا لمعرفة التفاصيل.', variables: ['name'] },
    schedule: { type: 'immediate' },
    status: 'Active',
    metrics: { sent: 200, delivered: 194, opened: 112, clicked: 38, converted: 5 },
    createdAt: '2026-05-15T08:00:00Z',
    createdBy: 'rep-003',
  },
  {
    id: 'camp-004',
    nameAr: 'حملة صيف ٢٠٢٦ — شقق جدة',
    type: 'ترويجية',
    descriptionAr: 'عروض خاصة على شقق جدة لصيف ٢٠٢٦',
    channels: ['WhatsApp', 'Social', 'Email'],
    audience: { city: ['جدة'], propertyInterest: ['شقة', 'دوبلكس'], estimatedReach: 820 },
    messageTemplate: { body: 'عروض الصيف في جدة — شقق فاخرة بدفعة أولى ١٠٪ فقط!', variables: ['name', 'city'] },
    schedule: { type: 'scheduled', scheduledAt: '2026-06-15T09:00:00Z' },
    status: 'Draft',
    metrics: { sent: 0, delivered: 0, opened: 0, clicked: 0, converted: 0 },
    createdAt: '2026-06-01T10:00:00Z',
    createdBy: 'rep-005',
  },
]

export const getCampaignById = (id: string) => CAMPAIGNS.find((c) => c.id === id)
