import type { Integration, AuditLogEntry } from '@/lib/types'

function auditLog(
  integrationId: string,
  endpoint: string,
  count: number,
  hasErrors = false
): AuditLogEntry[] {
  const methods = ['GET', 'POST', 'GET', 'PUT', 'GET'] as const
  const okCodes = [200, 200, 200, 201, 200]
  const errCodes = [400, 500, 503, 408]
  const base = new Date('2026-06-03T12:00:00Z').getTime()

  return Array.from({ length: count }, (_, i) => {
    const isError = hasErrors && (i === 3 || i === 11 || i === 24)
    const statusCode = isError ? errCodes[i % errCodes.length] : okCodes[i % okCodes.length]
    return {
      id: `${integrationId}-al-${i + 1}`,
      timestamp: new Date(base - i * 18 * 60 * 1000).toISOString(),
      method: methods[i % methods.length],
      endpoint,
      statusCode,
      duration: 80 + ((i * 37 + 13) % 820),
      records: statusCode >= 400 ? 0 : 10 + ((i * 53 + 7) % 490),
      errorMessage: statusCode >= 400 ? 'Request failed — retrying' : undefined,
    }
  })
}

export const INTEGRATIONS: Integration[] = [
  // ── هوية وتحقق (5) ───────────────────────────────────────────────────────
  {
    id: 'int-001',
    nameAr: 'أبشر — التحقق من الهوية',
    nameEn: 'Absher Identity',
    category: 'هوية وتحقق',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T12:00:00Z',
    recordCount: 128_450,
    description: 'التحقق الفوري من هوية العملاء عبر منصة أبشر الحكومية',
    auditLog: auditLog('int-001', '/v2/identity/verify', 50),
  },
  {
    id: 'int-002',
    nameAr: 'نافذ — التحقق بالهوية الوطنية',
    nameEn: 'Nafath NID',
    category: 'هوية وتحقق',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:58:00Z',
    recordCount: 94_210,
    description: 'خدمة التحقق بالهوية الوطنية والمقيم عبر تطبيق نافذ',
    auditLog: auditLog('int-002', '/api/nafath/verify', 50),
  },
  {
    id: 'int-003',
    nameAr: 'المركز الوطني للمعلومات',
    nameEn: 'National Information Center (NIC)',
    category: 'هوية وتحقق',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T06:00:00Z',
    recordCount: 215_800,
    description: 'مزامنة بيانات السجل المدني دفعيًا مع قاعدة بيانات NIC',
    auditLog: auditLog('int-003', '/batch/nic/sync', 30),
  },
  {
    id: 'int-004',
    nameAr: 'سمه — مكتب الائتمان السعودي',
    nameEn: 'SIMAH Credit Bureau',
    category: 'هوية وتحقق',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:45:00Z',
    recordCount: 47_320,
    description: 'الاستعلام عن التقرير الائتماني للعملاء للموافقة على التمويل',
    auditLog: auditLog('int-004', '/credit/report/query', 50),
  },
  {
    id: 'int-005',
    nameAr: 'أبشر أعمال',
    nameEn: 'Absher Business',
    category: 'هوية وتحقق',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T10:30:00Z',
    recordCount: 8_940,
    description: 'إدارة صلاحيات العمل والمنشآت التجارية',
    auditLog: auditLog('int-005', '/v1/business/auth', 20),
  },

  // ── بنوك وتمويل (8) ──────────────────────────────────────────────────────
  {
    id: 'int-006',
    nameAr: 'البنك الأهلي السعودي',
    nameEn: 'Saudi National Bank (SNB)',
    category: 'بنوك وتمويل',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:55:00Z',
    recordCount: 32_100,
    description: 'معالجة طلبات التمويل العقاري وتأكيد الدفعات',
    auditLog: auditLog('int-006', '/mortgage/application/submit', 50),
  },
  {
    id: 'int-007',
    nameAr: 'بنك الراجحي',
    nameEn: 'Al Rajhi Bank',
    category: 'بنوك وتمويل',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:50:00Z',
    recordCount: 28_760,
    description: 'التمويل العقاري والتقسيط الإسلامي',
    auditLog: auditLog('int-007', '/finance/real-estate/apply', 50),
  },
  {
    id: 'int-008',
    nameAr: 'بنك الرياض',
    nameEn: 'Riyad Bank',
    category: 'بنوك وتمويل',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T04:00:00Z',
    recordCount: 14_520,
    description: 'تسوية المدفوعات الدورية وكشوف الحسابات',
    auditLog: auditLog('int-008', '/batch/payment/settlement', 30),
  },
  {
    id: 'int-009',
    nameAr: 'بنك الإنماء',
    nameEn: 'Alinma Bank',
    category: 'بنوك وتمويل',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T05:00:00Z',
    recordCount: 11_340,
    description: 'خدمات التمويل المنزلي والمرابحة العقارية',
    auditLog: auditLog('int-009', '/home-finance/batch', 25),
  },
  {
    id: 'int-010',
    nameAr: 'مصرف الجزيرة',
    nameEn: 'Bank AlJazira',
    category: 'بنوك وتمويل',
    type: 'On-demand',
    status: 'Warning',
    lastSync: '2026-06-02T18:00:00Z',
    recordCount: 6_890,
    description: 'تمويل عقاري وخدمات بنكية إسلامية — تحذير: تأخر في الاستجابة',
    auditLog: auditLog('int-010', '/v1/mortgage/query', 40, true),
  },
  {
    id: 'int-011',
    nameAr: 'البنك السعودي للاستثمار',
    nameEn: 'Saudi Investment Bank (SAIB)',
    category: 'بنوك وتمويل',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T03:00:00Z',
    recordCount: 5_210,
    description: 'تمويل مشاريع عقارية تجارية وسكنية',
    auditLog: auditLog('int-011', '/batch/commercial/finance', 20),
  },
  {
    id: 'int-012',
    nameAr: 'البنك العربي الوطني',
    nameEn: 'Arab National Bank (ANB)',
    category: 'بنوك وتمويل',
    type: 'Batch',
    status: 'Warning',
    lastSync: '2026-06-02T22:00:00Z',
    recordCount: 9_870,
    description: 'خدمات التحويل والتسوية — تحذير: بطء في المزامنة الليلية',
    auditLog: auditLog('int-012', '/batch/transfer/reconcile', 35, true),
  },
  {
    id: 'int-013',
    nameAr: 'البنك السعودي الفرنسي',
    nameEn: 'Banque Saudi Fransi (BSF)',
    category: 'بنوك وتمويل',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T04:30:00Z',
    recordCount: 7_430,
    description: 'تمويل عقاري تجاري وخدمات الاستثمار',
    auditLog: auditLog('int-013', '/batch/real-estate/fund', 22),
  },

  // ── بوابات الدفع (3) ──────────────────────────────────────────────────────
  {
    id: 'int-014',
    nameAr: 'بيتابس',
    nameEn: 'PayTabs',
    category: 'بوابات الدفع',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:59:00Z',
    recordCount: 54_120,
    description: 'معالجة مدفوعات بطاقات الائتمان والمدى',
    auditLog: auditLog('int-014', '/v2/payment/charge', 50),
  },
  {
    id: 'int-015',
    nameAr: 'هايبر باي',
    nameEn: 'HyperPay',
    category: 'بوابات الدفع',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:57:00Z',
    recordCount: 38_900,
    description: 'بوابة دفع متعددة القنوات — كروت وتحويل وسداد',
    auditLog: auditLog('int-015', '/checkout/initiate', 50),
  },
  {
    id: 'int-016',
    nameAr: 'مدى',
    nameEn: 'Mada Payments',
    category: 'بوابات الدفع',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:56:00Z',
    recordCount: 72_340,
    description: 'معالجة مدفوعات شبكة مدى السعودية',
    auditLog: auditLog('int-016', '/mada/transaction/process', 50),
  },

  // ── حكومية وعقارية (6) ───────────────────────────────────────────────────
  {
    id: 'int-017',
    nameAr: 'هيئة العقار — REGA',
    nameEn: 'Real Estate General Authority (REGA)',
    category: 'حكومية وعقارية',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T02:00:00Z',
    recordCount: 18_650,
    description: 'مزامنة تراخيص التطوير العقاري وتسجيل الوحدات',
    auditLog: auditLog('int-017', '/rega/units/register', 30),
  },
  {
    id: 'int-018',
    nameAr: 'وزارة الإسكان',
    nameEn: 'Ministry of Housing (MoH)',
    category: 'حكومية وعقارية',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T01:00:00Z',
    recordCount: 42_100,
    description: 'ربط بيانات المشاريع السكنية مع قاعدة الوزارة',
    auditLog: auditLog('int-018', '/housing/projects/sync', 25),
  },
  {
    id: 'int-019',
    nameAr: 'منصة إيجار',
    nameEn: 'Ejar Platform',
    category: 'حكومية وعقارية',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:30:00Z',
    recordCount: 15_280,
    description: 'تسجيل عقود الإيجار وإدارة العلاقات التأجيرية',
    auditLog: auditLog('int-019', '/ejar/contract/register', 40),
  },
  {
    id: 'int-020',
    nameAr: 'برنامج سكني',
    nameEn: 'Sakani Program',
    category: 'حكومية وعقارية',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T10:00:00Z',
    recordCount: 89_340,
    description: 'التكامل مع برنامج سكني لدعم المواطنين في تملك السكن',
    auditLog: auditLog('int-020', '/sakani/beneficiary/check', 50),
  },
  {
    id: 'int-021',
    nameAr: 'وزارة العدل — كتابة العدل',
    nameEn: 'Ministry of Justice (MoJ)',
    category: 'حكومية وعقارية',
    type: 'On-demand',
    status: 'Active',
    lastSync: '2026-06-03T09:00:00Z',
    recordCount: 6_720,
    description: 'توثيق العقود وطلبات نقل الملكية عبر كتابة العدل',
    auditLog: auditLog('int-021', '/moj/notary/submit', 18),
  },
  {
    id: 'int-022',
    nameAr: 'السجل العقاري الموحد',
    nameEn: 'Unified Real Estate Registry',
    category: 'حكومية وعقارية',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T00:30:00Z',
    recordCount: 31_450,
    description: 'تسجيل ملكيات الوحدات ونقلها في السجل العقاري الموحد',
    auditLog: auditLog('int-022', '/registry/ownership/transfer', 28),
  },

  // ── اتصالات (3) ──────────────────────────────────────────────────────────
  {
    id: 'int-023',
    nameAr: 'STC — الاتصالات السعودية',
    nameEn: 'STC API',
    category: 'اتصالات',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:58:00Z',
    recordCount: 143_200,
    description: 'إرسال رسائل SMS عبر شبكة STC وتتبع حالة التسليم',
    auditLog: auditLog('int-023', '/sms/send', 50),
  },
  {
    id: 'int-024',
    nameAr: 'زين السعودية',
    nameEn: 'Zain API',
    category: 'اتصالات',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:55:00Z',
    recordCount: 67_890,
    description: 'بوابة SMS لشبكة زين',
    auditLog: auditLog('int-024', '/messaging/sms/dispatch', 50),
  },
  {
    id: 'int-025',
    nameAr: 'موبايلي',
    nameEn: 'Mobily API',
    category: 'اتصالات',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:52:00Z',
    recordCount: 52_340,
    description: 'بوابة SMS لشبكة موبايلي',
    auditLog: auditLog('int-025', '/api/sms/send', 50),
  },

  // ── قنوات التواصل (5) ─────────────────────────────────────────────────────
  {
    id: 'int-026',
    nameAr: 'واتساب بيزنس API',
    nameEn: 'WhatsApp Business API',
    category: 'قنوات التواصل',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T12:00:00Z',
    recordCount: 234_780,
    description: 'إرسال رسائل واتساب للعملاء وإدارة المحادثات',
    auditLog: auditLog('int-026', '/whatsapp/messages/send', 50),
  },
  {
    id: 'int-027',
    nameAr: 'يونيفونيك — بوابة SMS',
    nameEn: 'Unifonic SMS Gateway',
    category: 'قنوات التواصل',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:59:00Z',
    recordCount: 189_450,
    description: 'منصة موحدة لإرسال الرسائل القصيرة عبر شبكات متعددة',
    auditLog: auditLog('int-027', '/v2/messages/sms', 50),
  },
  {
    id: 'int-028',
    nameAr: 'SendGrid — البريد الإلكتروني',
    nameEn: 'SendGrid Email',
    category: 'قنوات التواصل',
    type: 'Batch',
    status: 'Error',
    lastSync: '2026-06-01T18:00:00Z',
    recordCount: 98_210,
    description: 'إرسال حملات البريد الإلكتروني — خطأ: انتهاء صلاحية API key',
    auditLog: auditLog('int-028', '/v3/mail/send', 50, true),
  },
  {
    id: 'int-029',
    nameAr: 'Firebase — الإشعارات الفورية',
    nameEn: 'Firebase Push Notifications',
    category: 'قنوات التواصل',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:58:00Z',
    recordCount: 78_920,
    description: 'إرسال إشعارات فورية لتطبيق الجوال',
    auditLog: auditLog('int-029', '/fcm/send', 50),
  },
  {
    id: 'int-030',
    nameAr: 'تويتر / X — التواصل الاجتماعي',
    nameEn: 'Twitter / X API',
    category: 'قنوات التواصل',
    type: 'On-demand',
    status: 'Active',
    lastSync: '2026-06-03T08:00:00Z',
    recordCount: 12_340,
    description: 'نشر المحتوى ومراقبة تغريدات مشاريع NHC',
    auditLog: auditLog('int-030', '/2/tweets', 20),
  },

  // ── ERP وCRM (4) ──────────────────────────────────────────────────────────
  {
    id: 'int-031',
    nameAr: 'SAP S/4HANA',
    nameEn: 'SAP S/4HANA',
    category: 'ERP & CRM',
    type: 'Batch',
    status: 'Warning',
    lastSync: '2026-06-02T12:00:00Z',
    recordCount: 456_780,
    description: 'نظام تخطيط موارد المؤسسة — تحذير: مزامنة الليل الأخير فشلت جزئيًا',
    auditLog: auditLog('int-031', '/sap/odata/v4/SalesOrder', 50, true),
  },
  {
    id: 'int-032',
    nameAr: 'Microsoft Dynamics 365',
    nameEn: 'Microsoft Dynamics 365',
    category: 'ERP & CRM',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T05:00:00Z',
    recordCount: 312_450,
    description: 'مزامنة بيانات المبيعات والعملاء مع Dynamics 365',
    auditLog: auditLog('int-032', '/api/data/v9.2/leads', 35),
  },
  {
    id: 'int-033',
    nameAr: 'Salesforce CRM',
    nameEn: 'Salesforce CRM',
    category: 'ERP & CRM',
    type: 'Real-time',
    status: 'Active',
    lastSync: '2026-06-03T11:45:00Z',
    recordCount: 287_630,
    description: 'مزامنة ثنائية الاتجاه مع Salesforce للعملاء والصفقات',
    auditLog: auditLog('int-033', '/services/data/v58.0/sobjects', 50),
  },
  {
    id: 'int-034',
    nameAr: 'Oracle ERP Cloud',
    nameEn: 'Oracle ERP Cloud',
    category: 'ERP & CRM',
    type: 'Batch',
    status: 'Error',
    lastSync: '2026-05-30T10:00:00Z',
    recordCount: 198_420,
    description: 'نظام Oracle للمحاسبة والمشتريات — خطأ: خادم غير متاح',
    auditLog: auditLog('int-034', '/fscmRestApi/resources/v11.13.18.05', 50, true),
  },

  // ── تحليلات وتقارير (3) ───────────────────────────────────────────────────
  {
    id: 'int-035',
    nameAr: 'Power BI — Microsoft',
    nameEn: 'Microsoft Power BI',
    category: 'تحليلات وتقارير',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T07:00:00Z',
    recordCount: 89_230,
    description: 'دفع بيانات المبيعات اليومية إلى لوحات Power BI التنفيذية',
    auditLog: auditLog('int-035', '/v1.0/myorg/datasets', 30),
  },
  {
    id: 'int-036',
    nameAr: 'Google Analytics 4',
    nameEn: 'Google Analytics 4',
    category: 'تحليلات وتقارير',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T06:30:00Z',
    recordCount: 1_234_560,
    description: 'تتبع تفاعل الزوار مع الموقع وحملات التسويق الرقمي',
    auditLog: auditLog('int-036', '/v1beta/properties/data:runReport', 40),
  },
  {
    id: 'int-037',
    nameAr: 'Snowflake — مستودع البيانات',
    nameEn: 'Snowflake Data Warehouse',
    category: 'تحليلات وتقارير',
    type: 'Batch',
    status: 'Active',
    lastSync: '2026-06-03T03:30:00Z',
    recordCount: 5_678_900,
    description: 'مستودع البيانات المركزي — تحميل يومي لجميع بيانات CRM والمبيعات',
    auditLog: auditLog('int-037', '/api/v2/statements', 35),
  },
]

// Summary counts: Active=32, Warning=3, Error=2 — total=37
export const INTEGRATION_SUMMARY = {
  total: 37,
  active: 32,
  warning: 3,
  error: 2,
}

export const getIntegrationById = (id: string) =>
  INTEGRATIONS.find((i) => i.id === id)
