import type { Journey } from '@/lib/types'

export const JOURNEYS: Journey[] = [
  {
    id: 'jrn-001',
    nameAr: 'رحلة العميل الجديد',
    descriptionAr: 'تسلسل ترحيبي تلقائي للعملاء المحتملين الجدد من الويب',
    status: 'Active',
    trigger: 'lead_created',
    enrolledCount: 68,
    completedCount: 24,
    createdAt: '2026-03-01T08:00:00Z',
    activatedAt: '2026-03-05T09:00:00Z',
    nodes: [
      { id: 'n1', type: 'trigger', position: { x: 300, y: 50  }, data: { labelAr: 'عميل جديد', type: 'trigger', config: { event: 'lead_created' } } },
      { id: 'n2', type: 'action',  position: { x: 300, y: 160 }, data: { labelAr: 'إرسال رسالة ترحيب', subLabelAr: 'واتساب', type: 'action', config: { channel: 'WhatsApp', templateId: 'welcome' } } },
      { id: 'n3', type: 'delay',   position: { x: 300, y: 270 }, data: { labelAr: 'انتظار ٢٤ ساعة', type: 'delay', config: { hours: 24 } } },
      { id: 'n4', type: 'condition', position: { x: 300, y: 380 }, data: { labelAr: 'هل فتح الرسالة؟', type: 'condition', config: { check: 'opened_message' } } },
      { id: 'n5', type: 'action',  position: { x: 520, y: 500 }, data: { labelAr: 'إرسال كتالوج المشاريع', subLabelAr: 'واتساب — المسار الإيجابي', type: 'action', config: { channel: 'WhatsApp', templateId: 'catalog' } } },
      { id: 'n6', type: 'action',  position: { x:  80, y: 500 }, data: { labelAr: 'إعادة الإرسال بـ SMS', subLabelAr: 'المسار البديل', type: 'action', config: { channel: 'SMS', templateId: 'welcome_sms' } } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
      { id: 'e4', source: 'n4', target: 'n5', label: 'نعم', animated: true },
      { id: 'e5', source: 'n4', target: 'n6', label: 'لا' },
    ],
  },
  {
    id: 'jrn-002',
    nameAr: 'رحلة إعادة تفعيل العملاء',
    descriptionAr: 'تسلسل آلي للعملاء غير النشطين منذ أكثر من ٣٠ يوماً',
    status: 'Paused',
    trigger: 'inactive_30_days',
    enrolledCount: 42,
    completedCount: 15,
    createdAt: '2026-04-10T10:00:00Z',
    activatedAt: '2026-04-15T09:00:00Z',
    nodes: [
      { id: 'n1', type: 'trigger', position: { x: 300, y: 50  }, data: { labelAr: 'عدم نشاط ٣٠ يوم', type: 'trigger', config: { event: 'inactive_30_days' } } },
      { id: 'n2', type: 'action',  position: { x: 300, y: 160 }, data: { labelAr: 'إرسال رسالة إعادة تفعيل', subLabelAr: 'SMS + Email', type: 'action', config: { channels: ['SMS', 'Email'], templateId: 'reactivate' } } },
      { id: 'n3', type: 'delay',   position: { x: 300, y: 270 }, data: { labelAr: 'انتظار ٧٢ ساعة', type: 'delay', config: { hours: 72 } } },
      { id: 'n4', type: 'condition', position: { x: 300, y: 380 }, data: { labelAr: 'هل تجاوب؟', type: 'condition', config: { check: 'any_interaction' } } },
      { id: 'n5', type: 'action',  position: { x: 520, y: 500 }, data: { labelAr: 'تنبيه المندوب', subLabelAr: 'مكالمة يدوية', type: 'action', config: { assignTo: 'sales_rep', action: 'manual_call' } } },
      { id: 'n6', type: 'action',  position: { x:  80, y: 500 }, data: { labelAr: 'نقل لقائمة الخاملين', subLabelAr: 'تعليق متابعة', type: 'action', config: { action: 'archive_lead' } } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
      { id: 'e4', source: 'n4', target: 'n5', label: 'نعم', animated: true },
      { id: 'e5', source: 'n4', target: 'n6', label: 'لا' },
    ],
  },
  {
    id: 'jrn-003',
    nameAr: 'رحلة إتمام الصفقة',
    descriptionAr: 'تتبع العميل من مرحلة العرض حتى التوقيع وتسليم المستندات',
    status: 'Draft',
    trigger: 'stage_changed',
    enrolledCount: 0,
    completedCount: 0,
    createdAt: '2026-06-01T09:00:00Z',
    nodes: [
      { id: 'n1', type: 'trigger', position: { x: 300, y: 50  }, data: { labelAr: 'تغيير مرحلة: عرض سعر', type: 'trigger', config: { event: 'stage_changed', toStage: 'Proposal' } } },
      { id: 'n2', type: 'action',  position: { x: 300, y: 160 }, data: { labelAr: 'إرسال عرض السعر', subLabelAr: 'واتساب + Email', type: 'action', config: { channels: ['WhatsApp', 'Email'], templateId: 'proposal' } } },
      { id: 'n3', type: 'delay',   position: { x: 300, y: 270 }, data: { labelAr: 'انتظار ٤٨ ساعة', type: 'delay', config: { hours: 48 } } },
      { id: 'n4', type: 'condition', position: { x: 300, y: 380 }, data: { labelAr: 'هل درجة AI > ٧٠؟', type: 'condition', config: { check: 'ai_score_gt', value: 70 } } },
      { id: 'n5', type: 'action',  position: { x: 520, y: 500 }, data: { labelAr: 'تعيين مندوب أول', subLabelAr: 'متابعة عاجلة', type: 'action', config: { assignTo: 'senior_rep' } } },
      { id: 'n6', type: 'action',  position: { x:  80, y: 500 }, data: { labelAr: 'إرسال تذكير بالعرض', subLabelAr: 'SMS', type: 'action', config: { channel: 'SMS', templateId: 'reminder' } } },
      { id: 'n7', type: 'delay',   position: { x: 300, y: 620 }, data: { labelAr: 'انتظار يومَين إضافيَّين', type: 'delay', config: { hours: 48 } } },
      { id: 'n8', type: 'action',  position: { x: 300, y: 730 }, data: { labelAr: 'تحديث حالة العميل', subLabelAr: 'بناءً على الاستجابة', type: 'action', config: { action: 'update_stage' } } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n2' },
      { id: 'e2', source: 'n2', target: 'n3' },
      { id: 'e3', source: 'n3', target: 'n4' },
      { id: 'e4', source: 'n4', target: 'n5', label: 'نعم', animated: true },
      { id: 'e5', source: 'n4', target: 'n6', label: 'لا' },
      { id: 'e6', source: 'n5', target: 'n7' },
      { id: 'e7', source: 'n6', target: 'n7' },
      { id: 'e8', source: 'n7', target: 'n8' },
    ],
  },
]

export const getJourneyById = (id: string) => JOURNEYS.find((j) => j.id === id)
