import type { LeadScore } from '@/lib/types'

export const LEAD_SCORES: LeadScore[] = [
  // ── New ───────────────────────────────────────────────────────────────────────
  {
    leadId: 'lead-001',
    totalScore: 47,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-06-03T09:00:00Z',
    topFactors: ['اهتمام أولي بالأراضي', 'تفاعل عبر الموقع'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 11, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 12, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 8, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 7, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-002',
    totalScore: 52,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-06-02T14:00:00Z',
    topFactors: ['تفاعل متوسط عبر السوشيال'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 12, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 10, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 8, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-003',
    totalScore: 44,
    maxScore: 100,
    grade: 'D',
    trend: 'down',
    updatedAt: '2026-06-01T10:00:00Z',
    topFactors: ['ردود بطيئة على الحملة'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 11, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 9, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 8, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 7, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-004',
    totalScore: 61,
    maxScore: 100,
    grade: 'C',
    trend: 'up',
    updatedAt: '2026-05-31T16:00:00Z',
    topFactors: ['ميزانية مرتفعة', 'اهتمام بفيلا في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 5, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 17, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 15, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 12, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 12, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-005',
    totalScore: 39,
    maxScore: 100,
    grade: 'D',
    trend: 'down',
    updatedAt: '2026-06-03T08:00:00Z',
    topFactors: ['تفاعل محدود حتى الآن'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 4, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 8, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 10, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 8, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 9, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-006',
    totalScore: 73,
    maxScore: 100,
    grade: 'B',
    trend: 'stable',
    updatedAt: '2026-06-02T10:00:00Z',
    topFactors: ['إحالة مباشرة', 'ميزانية مناسبة'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 17, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 18, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 12, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 9, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-025',
    totalScore: 55,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-06-03T07:30:00Z',
    topFactors: ['تفاعل جيد عبر الموقع'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 11, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 12, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 10, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-026',
    totalScore: 68,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-06-02T12:00:00Z',
    topFactors: ['إحالة موثوقة', 'ميزانية مرتفعة', 'اهتمام بفيلا في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 6, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 19, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 13, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-027',
    totalScore: 43,
    maxScore: 100,
    grade: 'D',
    trend: 'stable',
    updatedAt: '2026-06-01T16:00:00Z',
    topFactors: ['وصل عبر حملة تسويقية'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 4, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 12, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 10, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 10, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 7, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-028',
    totalScore: 79,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-06-03T10:00:00Z',
    topFactors: ['ميزانية عالية جداً', 'قابلناه في المعرض', 'اهتمام بفيلا فاخرة'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 12, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 22, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 14, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 14, maxScore: 15, weight: 0.15 },
    ],
  },

  // ── Contacted ─────────────────────────────────────────────────────────────────
  {
    leadId: 'lead-007',
    totalScore: 58,
    maxScore: 100,
    grade: 'C',
    trend: 'up',
    updatedAt: '2026-05-29T10:00:00Z',
    topFactors: ['تواصل نشط عبر واتساب'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 18, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 10, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 11, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 10, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-008',
    totalScore: 66,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-28T14:00:00Z',
    topFactors: ['ميزانية مرتفعة', 'اهتمام بفيلا في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 19, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 12, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 13, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-009',
    totalScore: 49,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-05-30T11:00:00Z',
    topFactors: ['تفاعل عبر السوشيال ميديا'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 10, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 9, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 12, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-010',
    totalScore: 54,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-06-01T09:00:00Z',
    topFactors: ['اهتمام بدوبلكس في الدمام'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 12, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 14, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 7, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 11, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 10, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-011',
    totalScore: 71,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-27T15:00:00Z',
    topFactors: ['قابلناها في معرض سيتي سكيب', 'تفاعل نشط'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 17, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 15, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 16, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 12, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 11, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-029',
    totalScore: 46,
    maxScore: 100,
    grade: 'C',
    trend: 'down',
    updatedAt: '2026-05-31T13:00:00Z',
    topFactors: ['تفاعل متوسط'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 8, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 9, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 11, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-030',
    totalScore: 63,
    maxScore: 100,
    grade: 'C',
    trend: 'up',
    updatedAt: '2026-05-30T09:00:00Z',
    topFactors: ['إحالة موثوقة', 'مهتمة بمشروع نجران هيلز'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 16, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 8, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-031',
    totalScore: 57,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-05-29T14:00:00Z',
    topFactors: ['اهتمام بدوبلكس في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 11, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 11, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 13, maxScore: 15, weight: 0.15 },
    ],
  },

  // ── Qualified ─────────────────────────────────────────────────────────────────
  {
    leadId: 'lead-012',
    totalScore: 65,
    maxScore: 100,
    grade: 'B',
    trend: 'stable',
    updatedAt: '2026-05-25T10:00:00Z',
    topFactors: ['إحالة مباشرة', 'مؤهل مالياً'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 15, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 16, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 11, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 10, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-013',
    totalScore: 77,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-28T09:00:00Z',
    topFactors: ['اهتمام بفيلا عالية القيمة', 'تفاعل جيد عبر الويب'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 19, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 20, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 14, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 11, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-014',
    totalScore: 60,
    maxScore: 100,
    grade: 'C',
    trend: 'up',
    updatedAt: '2026-05-26T14:00:00Z',
    topFactors: ['تفاعل عالٍ رغم ميزانية محدودة'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 22, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 10, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 11, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 8, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-015',
    totalScore: 82,
    maxScore: 100,
    grade: 'A',
    trend: 'up',
    updatedAt: '2026-06-01T10:00:00Z',
    topFactors: ['إحالة من عميل VIP', 'ميزانية مرتفعة', 'تفاعل نشط'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 22, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 20, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 18, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 14, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 8, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-032',
    totalScore: 74,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-27T11:00:00Z',
    topFactors: ['قابلناها في المعرض', 'اهتمام بتاون هاوس في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 16, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 16, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 12, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 13, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-033',
    totalScore: 70,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-24T15:00:00Z',
    topFactors: ['تأهيل مالي مكتمل', 'إحالة موثوقة', 'جاهز للعرض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 10, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 18, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 17, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 12, maxScore: 15, weight: 0.15 },
    ],
  },

  // ── Proposal ──────────────────────────────────────────────────────────────────
  {
    leadId: 'lead-016',
    totalScore: 41,
    maxScore: 100,
    grade: 'D',
    trend: 'down',
    updatedAt: '2026-05-20T11:00:00Z',
    topFactors: ['عرض سعر مُرسل لكن التفاعل تراجع'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 2, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 9, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 12, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 8, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 10, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-017',
    totalScore: 74,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-22T09:00:00Z',
    topFactors: ['ميزانية مرتفعة', 'تفاعل ممتاز'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 19, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 18, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 12, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 13, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 12, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-018',
    totalScore: 69,
    maxScore: 100,
    grade: 'B',
    trend: 'up',
    updatedAt: '2026-05-24T13:00:00Z',
    topFactors: ['إحالة موثوقة', 'تفاعل جيد'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 16, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 14, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 16, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 11, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 12, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-019',
    totalScore: 56,
    maxScore: 100,
    grade: 'C',
    trend: 'stable',
    updatedAt: '2026-05-18T10:00:00Z',
    topFactors: ['اهتمام بأرض في الرياض'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 14, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 7, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 9, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 13, maxScore: 15, weight: 0.15 },
    ],
  },
  {
    leadId: 'lead-034',
    totalScore: 83,
    maxScore: 100,
    grade: 'A',
    trend: 'up',
    updatedAt: '2026-05-21T10:00:00Z',
    topFactors: ['ميزانية عالية جداً', 'عرض سعر مُرسل', 'إحالة VIP'],
    factors: [
      { labelAr: 'مدى كثافة تفاعله معك', score: 13, maxScore: 25, weight: 0.25 },
      { labelAr: 'القدرة المالية (الميزانية)', score: 24, maxScore: 25, weight: 0.25 },
      { labelAr: 'قوة مصدر العميل (من أين جاء؟)', score: 18, maxScore: 20, weight: 0.2 },
      { labelAr: 'نوع العقار الذي يهتمّ به', score: 14, maxScore: 15, weight: 0.15 },
      { labelAr: 'موقع المدينة وأهميتها', score: 14, maxScore: 15, weight: 0.15 },
    ],
  },
]

export const getLeadScore = (leadId: string) =>
  LEAD_SCORES.find((s) => s.leadId === leadId)
